package com.sobey.cmdbuild.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DeviceSpecHistory generated by hbm2java
 */
@Entity
@Table(name = "device_spec_history", schema = "public")
public class DeviceSpecHistory extends BasicEntity {

	private Integer brand;
	private String cpuModel;
	private Integer cpuNumber;
	private DeviceSpec deviceSpec;
	private Integer deviceType;
	private Date endDate;
	private Integer hdNumber;
	private Integer height;
	private Integer maintenance;
	private Integer nicNumber;
	private Integer power;
	private Double price;
	private Integer ramNumber;
	private String remark;

	public DeviceSpecHistory() {
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"BeginDate\"", nullable = false, length = 29)
	public Date getBeginDate() {
		return this.beginDate;
	}

	@Column(name = "\"Brand\"")
	public Integer getBrand() {
		return this.brand;
	}

	@Column(name = "\"Code\"", length = 100)
	public String getCode() {
		return this.code;
	}

	@Column(name = "cpu_model", length = 100)
	public String getCpuModel() {
		return this.cpuModel;
	}

	@Column(name = "cpu_number")
	public Integer getCpuNumber() {
		return this.cpuNumber;
	}

	@Column(name = "\"Description\"", length = 250)
	public String getDescription() {
		return this.description;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public DeviceSpec getDeviceSpec() {
		return this.deviceSpec;
	}

	@Column(name = "device_type")
	public Integer getDeviceType() {
		return this.deviceType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"EndDate\"", nullable = false, length = 29)
	public Date getEndDate() {
		return this.endDate;
	}

	@Column(name = "hd_number")
	public Integer getHdNumber() {
		return this.hdNumber;
	}

	@Column(name = "\"Height\"")
	public Integer getHeight() {
		return this.height;
	}

	@Column(name = "\"Maintenance\"")
	public Integer getMaintenance() {
		return this.maintenance;
	}

	@Column(name = "nic_number")
	public Integer getNicNumber() {
		return this.nicNumber;
	}

	@Column(name = "\"Notes\"")
	public String getNotes() {
		return this.notes;
	}

	@Column(name = "\"Power\"")
	public Integer getPower() {
		return this.power;
	}

	@Column(name = "\"Price\"", precision = 17, scale = 17)
	public Double getPrice() {
		return this.price;
	}

	@Column(name = "ram_number")
	public Integer getRamNumber() {
		return this.ramNumber;
	}

	@Column(name = "\"Remark\"", length = 250)
	public String getRemark() {
		return this.remark;
	}

	@Column(name = "\"Status\"", length = 1)
	public Character getStatus() {
		return this.status;
	}

	@Column(name = "\"User\"", length = 40)
	public String getUser() {
		return this.user;
	}

	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	public void setBrand(Integer brand) {
		this.brand = brand;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public void setCpuModel(String cpuModel) {
		this.cpuModel = cpuModel;
	}

	public void setCpuNumber(Integer cpuNumber) {
		this.cpuNumber = cpuNumber;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setDeviceSpec(DeviceSpec deviceSpec) {
		this.deviceSpec = deviceSpec;
	}

	public void setDeviceType(Integer deviceType) {
		this.deviceType = deviceType;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public void setHdNumber(Integer hdNumber) {
		this.hdNumber = hdNumber;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	public void setMaintenance(Integer maintenance) {
		this.maintenance = maintenance;
	}

	public void setNicNumber(Integer nicNumber) {
		this.nicNumber = nicNumber;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public void setPower(Integer power) {
		this.power = power;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public void setRamNumber(Integer ramNumber) {
		this.ramNumber = ramNumber;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	public void setUser(String user) {
		this.user = user;
	}

}
