package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ecs generated by hbm2java
 */
@Entity
@Table(name = "ecs", schema = "public")
public class Ecs extends BasicEntity {

	private Integer ecsAgent;
	private Set<EcsHistory> ecsHistories = new HashSet<EcsHistory>(0);
	private Integer ecsSpec;
	private Integer ecsStatus;
	private Integer image;
	private Integer ipaddress;
	private String remark;
	private Integer server;
	private Integer tag;
	private Integer tenants;

	public Ecs() {
	}

	@Column(name = "ecs_agent")
	public Integer getEcsAgent() {
		return this.ecsAgent;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecs")
	public Set<EcsHistory> getEcsHistories() {
		return this.ecsHistories;
	}

	@Column(name = "ecs_spec")
	public Integer getEcsSpec() {
		return this.ecsSpec;
	}

	@Column(name = "ecs_status")
	public Integer getEcsStatus() {
		return this.ecsStatus;
	}

	@Column(name = "\"Image\"")
	public Integer getImage() {
		return this.image;
	}

	@Column(name = "ipaddress")
	public Integer getIpaddress() {
		return this.ipaddress;
	}

	@Column(name = "\"Remark\"", length = 250)
	public String getRemark() {
		return this.remark;
	}

	@Column(name = "server")
	public Integer getServer() {
		return this.server;
	}

	@Column(name = "tag")
	public Integer getTag() {
		return this.tag;
	}

	@Column(name = "tenants")
	public Integer getTenants() {
		return this.tenants;
	}

	public void setEcsAgent(Integer ecsAgent) {
		this.ecsAgent = ecsAgent;
	}

	public void setEcsHistories(Set<EcsHistory> ecsHistories) {
		this.ecsHistories = ecsHistories;
	}

	public void setEcsSpec(Integer ecsSpec) {
		this.ecsSpec = ecsSpec;
	}

	public void setEcsStatus(Integer ecsStatus) {
		this.ecsStatus = ecsStatus;
	}

	public void setImage(Integer image) {
		this.image = image;
	}

	public void setIpaddress(Integer ipaddress) {
		this.ipaddress = ipaddress;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public void setServer(Integer server) {
		this.server = server;
	}

	public void setTag(Integer tag) {
		this.tag = tag;
	}

	public void setTenants(Integer tenants) {
		this.tenants = tenants;
	}

}
