package com.sobey.cmdbuild.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EcsHistory generated by hbm2java
 */
@Entity
@Table(name = "ecs_history", schema = "public")
public class EcsHistory extends BasicEntity {

	private Ecs ecs;
	private Integer ecsAgent;
	private Integer ecsSpec;
	private Integer ecsStatus;
	private Date endDate;
	private Integer image;
	private Integer ipaddress;
	private String remark;
	private Integer server;
	private Integer tag;
	private Integer tenants;

	public EcsHistory() {
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public Ecs getEcs() {
		return this.ecs;
	}

	@Column(name = "ecs_agent")
	public Integer getEcsAgent() {
		return this.ecsAgent;
	}

	@Column(name = "ecs_spec")
	public Integer getEcsSpec() {
		return this.ecsSpec;
	}

	@Column(name = "ecs_status")
	public Integer getEcsStatus() {
		return this.ecsStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"EndDate\"", nullable = false, length = 29)
	public Date getEndDate() {
		return this.endDate;
	}

	@Column(name = "\"Image\"")
	public Integer getImage() {
		return this.image;
	}

	@Column(name = "ipaddress")
	public Integer getIpaddress() {
		return this.ipaddress;
	}

	@Column(name = "\"Remark\"", length = 250)
	public String getRemark() {
		return this.remark;
	}

	@Column(name = "server")
	public Integer getServer() {
		return this.server;
	}

	@Column(name = "tag")
	public Integer getTag() {
		return this.tag;
	}

	@Column(name = "tenants")
	public Integer getTenants() {
		return this.tenants;
	}

	public void setEcs(Ecs ecs) {
		this.ecs = ecs;
	}

	public void setEcsAgent(Integer ecsAgent) {
		this.ecsAgent = ecsAgent;
	}

	public void setEcsSpec(Integer ecsSpec) {
		this.ecsSpec = ecsSpec;
	}

	public void setEcsStatus(Integer ecsStatus) {
		this.ecsStatus = ecsStatus;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public void setImage(Integer image) {
		this.image = image;
	}

	public void setIpaddress(Integer ipaddress) {
		this.ipaddress = ipaddress;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public void setServer(Integer server) {
		this.server = server;
	}

	public void setTag(Integer tag) {
		this.tag = tag;
	}

	public void setTenants(Integer tenants) {
		this.tenants = tenants;
	}

}
