package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EcsSpec generated by hbm2java
 */
@Entity
@Table(name = "ecs_spec", schema = "public")
public class EcsSpec extends BasicEntity {

	private Integer cpuNumber;
	private Integer diskSize;
	private Set<EcsSpecHistory> ecsSpecHistories = new HashSet<EcsSpecHistory>(0);
	private Integer memory;
	private Double price;
	private String remark;
	private Integer brand;

	public EcsSpec() {
	}

	@Column(name = "\"Brand\"")
	public Integer getBrand() {
		return brand;
	}

	@Column(name = "cpu_number")
	public Integer getCpuNumber() {
		return this.cpuNumber;
	}

	@Column(name = "disk_size")
	public Integer getDiskSize() {
		return this.diskSize;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecsSpec")
	public Set<EcsSpecHistory> getEcsSpecHistories() {
		return this.ecsSpecHistories;
	}

	@Column(name = "\"Memory\"")
	public Integer getMemory() {
		return this.memory;
	}

	@Column(name = "\"Price\"", precision = 17, scale = 17)
	public Double getPrice() {
		return this.price;
	}

	@Column(name = "\"Remark\"", length = 250)
	public String getRemark() {
		return this.remark;
	}

	public void setCpuNumber(Integer cpuNumber) {
		this.cpuNumber = cpuNumber;
	}

	public void setDiskSize(Integer diskSize) {
		this.diskSize = diskSize;
	}

	public void setEcsSpecHistories(Set<EcsSpecHistory> ecsSpecHistories) {
		this.ecsSpecHistories = ecsSpecHistories;
	}

	public void setMemory(Integer memory) {
		this.memory = memory;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public void setBrand(Integer brand) {
		this.brand = brand;
	}

}
