package com.sobey.cmdbuild.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;

import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EcsSpec generated by hbm2java
 */
@Entity
@Table(name = "ecs_spec", schema = "public")
public class EcsSpec extends BasicEntity {

	private Integer cpuNumber;
	private Integer diskSize;
	private Set<EcsSpecHistory> ecsSpecHistories = new HashSet<EcsSpecHistory>(0);
	private Integer memory;
	private Double price;
	private String remark;

	public EcsSpec() {
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"BeginDate\"", nullable = false, length = 29)
	public Date getBeginDate() {
		return this.beginDate;
	}

	@Column(name = "\"Code\"", length = 100)
	public String getCode() {
		return this.code;
	}

	@Column(name = "cpu_number")
	public Integer getCpuNumber() {
		return this.cpuNumber;
	}

	@Column(name = "\"Description\"", length = 250)
	public String getDescription() {
		return this.description;
	}

	@Column(name = "disk_size")
	public Integer getDiskSize() {
		return this.diskSize;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ecsSpec")
	public Set<EcsSpecHistory> getEcsSpecHistories() {
		return this.ecsSpecHistories;
	}

	@Column(name = "\"Memory\"")
	public Integer getMemory() {
		return this.memory;
	}

	@Column(name = "\"Notes\"")
	public String getNotes() {
		return this.notes;
	}

	@Column(name = "\"Price\"", precision = 17, scale = 17)
	public Double getPrice() {
		return this.price;
	}

	@Column(name = "\"Remark\"", length = 250)
	public String getRemark() {
		return this.remark;
	}

	@Column(name = "\"Status\"", length = 1)
	public Character getStatus() {
		return this.status;
	}

	@Column(name = "\"User\"", length = 40)
	public String getUser() {
		return this.user;
	}

	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public void setCpuNumber(Integer cpuNumber) {
		this.cpuNumber = cpuNumber;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setDiskSize(Integer diskSize) {
		this.diskSize = diskSize;
	}

	public void setEcsSpecHistories(Set<EcsSpecHistory> ecsSpecHistories) {
		this.ecsSpecHistories = ecsSpecHistories;
	}

	public void setMemory(Integer memory) {
		this.memory = memory;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	public void setUser(String user) {
		this.user = user;
	}

}
