package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Eip generated by hbm2java
 */
@Entity
@Table(name = "eip", schema = "public")
public class Eip extends BasicEntity {

	private Integer bandwidth;
	private Set<EipHistory> eipHistories = new HashSet<EipHistory>(0);
	private Integer eipSpec;
	private Integer eipStatus;
	private Integer ipaddress;
	private String remark;
	private Integer tag;
	private Integer tenants;

	public Eip() {
	}

	@Column(name = "bandwidth")
	public Integer getBandwidth() {
		return this.bandwidth;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eip")
	public Set<EipHistory> getEipHistories() {
		return this.eipHistories;
	}

	@Column(name = "eip_spec")
	public Integer getEipSpec() {
		return this.eipSpec;
	}

	@Column(name = "eip_status")
	public Integer getEipStatus() {
		return this.eipStatus;
	}

	@Column(name = "\"IPAddress\"")
	public Integer getIpaddress() {
		return this.ipaddress;
	}

	@Column(name = "\"Remark\"", length = 250)
	public String getRemark() {
		return this.remark;
	}

	@Column(name = "tag")
	public Integer getTag() {
		return this.tag;
	}

	@Column(name = "tenants")
	public Integer getTenants() {
		return this.tenants;
	}

	public void setBandwidth(Integer bandwidth) {
		this.bandwidth = bandwidth;
	}

	public void setEipHistories(Set<EipHistory> eipHistories) {
		this.eipHistories = eipHistories;
	}

	public void setEipSpec(Integer eipSpec) {
		this.eipSpec = eipSpec;
	}

	public void setEipStatus(Integer eipStatus) {
		this.eipStatus = eipStatus;
	}

	public void setIpaddress(Integer ipaddress) {
		this.ipaddress = ipaddress;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public void setTag(Integer tag) {
		this.tag = tag;
	}

	public void setTenants(Integer tenants) {
		this.tenants = tenants;
	}

}
