package com.sobey.cmdbuild.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;

import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EipHistory generated by hbm2java
 */
@Entity
@Table(name = "eip_history", schema = "public")
public class EipHistory extends BasicEntity {

	private Integer bandwidth;

	private Eip eip;
	private Integer eipSpec;
	private Integer eipStatus;
	private Date endDate;
	private Integer ipaddress;
	private String remark;
	private Integer tag;
	private Integer tenants;

	public EipHistory() {
	}

	@Column(name = "bandwidth")
	public Integer getBandwidth() {
		return this.bandwidth;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"BeginDate\"", nullable = false, length = 29)
	public Date getBeginDate() {
		return this.beginDate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public Eip getEip() {
		return this.eip;
	}

	@Column(name = "eip_spec")
	public Integer getEipSpec() {
		return this.eipSpec;
	}

	@Column(name = "eip_status")
	public Integer getEipStatus() {
		return this.eipStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"EndDate\"", nullable = false, length = 29)
	public Date getEndDate() {
		return this.endDate;
	}

	@Column(name = "\"IPAddress\"")
	public Integer getIpaddress() {
		return this.ipaddress;
	}

	@Column(name = "\"Remark\"", length = 250)
	public String getRemark() {
		return this.remark;
	}

	@Column(name = "tag")
	public Integer getTag() {
		return this.tag;
	}

	@Column(name = "tenants")
	public Integer getTenants() {
		return this.tenants;
	}

	public void setBandwidth(Integer bandwidth) {
		this.bandwidth = bandwidth;
	}

	public void setEip(Eip eip) {
		this.eip = eip;
	}

	public void setEipSpec(Integer eipSpec) {
		this.eipSpec = eipSpec;
	}

	public void setEipStatus(Integer eipStatus) {
		this.eipStatus = eipStatus;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public void setIpaddress(Integer ipaddress) {
		this.ipaddress = ipaddress;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public void setTag(Integer tag) {
		this.tag = tag;
	}

	public void setTenants(Integer tenants) {
		this.tenants = tenants;
	}

}
