package com.sobey.cmdbuild.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;

import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EipPolicyHistory generated by hbm2java
 */
@Entity
@Table(name = "eip_policy_history", schema = "public")
public class EipPolicyHistory extends BasicEntity {

	private Integer eip;
	private EipPolicy eipPolicy;
	private Date endDate;
	private Integer protocol;
	private Integer sourcePort;
	private Integer targetPort;

	public EipPolicyHistory() {
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"BeginDate\"", nullable = false, length = 29)
	public Date getBeginDate() {
		return this.beginDate;
	}

	@Column(name = "eip")
	public Integer getEip() {
		return this.eip;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public EipPolicy getEipPolicy() {
		return this.eipPolicy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"EndDate\"", nullable = false, length = 29)
	public Date getEndDate() {
		return this.endDate;
	}

	@Column(name = "protocol")
	public Integer getProtocol() {
		return this.protocol;
	}

	@Column(name = "source_port")
	public Integer getSourcePort() {
		return this.sourcePort;
	}

	@Column(name = "target_port")
	public Integer getTargetPort() {
		return this.targetPort;
	}

	public void setEip(Integer eip) {
		this.eip = eip;
	}

	public void setEipPolicy(EipPolicy eipPolicy) {
		this.eipPolicy = eipPolicy;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public void setProtocol(Integer protocol) {
		this.protocol = protocol;
	}

	public void setSourcePort(Integer sourcePort) {
		this.sourcePort = sourcePort;
	}

	public void setTargetPort(Integer targetPort) {
		this.targetPort = targetPort;
	}

}
