package com.sobey.cmdbuild.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EipSpecHistory generated by hbm2java
 */
@Entity
@Table(name = "eip_spec_history", schema = "public")
public class EipSpecHistory extends BasicEntity {

	private EipSpec eipSpec;
	private Date endDate;
	private Double price;
	private String remark;
	private Integer isp;
	private Integer brand;

	public EipSpecHistory() {
	}

	@Column(name = "\"Brand\"")
	public Integer getBrand() {
		return brand;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public EipSpec getEipSpec() {
		return this.eipSpec;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"EndDate\"", nullable = false, length = 29)
	public Date getEndDate() {
		return this.endDate;
	}

	@Column(name = "\"Price\"", precision = 17, scale = 17)
	public Double getPrice() {
		return this.price;
	}

	@Column(name = "\"Remark\"", length = 250)
	public String getRemark() {
		return this.remark;
	}

	@Column(name = "\"ISP\"")
	public Integer getIsp() {
		return isp;
	}

	public void setBrand(Integer brand) {
		this.brand = brand;
	}

	public void setEipSpec(EipSpec eipSpec) {
		this.eipSpec = eipSpec;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public void setIsp(Integer isp) {
		this.isp = isp;
	}

}
