package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EipSpec generated by hbm2java
 */
@Entity
@Table(name = "eip_spec", schema = "public")
public class EipSpec extends BasicEntity {

	private Set<EipSpecHistory> eipSpecHistories = new HashSet<EipSpecHistory>(0);
	private Double price;
	private String remark;
	private Integer isp;
	private Integer brand;

	public EipSpec() {
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eipSpec")
	public Set<EipSpecHistory> getEipSpecHistories() {
		return this.eipSpecHistories;
	}

	@Column(name = "\"Brand\"")
	public Integer getBrand() {
		return brand;
	}

	@Column(name = "\"Price\"", precision = 17, scale = 17)
	public Double getPrice() {
		return this.price;
	}

	@Column(name = "\"Remark\"", length = 250)
	public String getRemark() {
		return this.remark;
	}

	@Column(name = "\"ISP\"")
	public Integer getIsp() {
		return isp;
	}

	public void setEipSpecHistories(Set<EipSpecHistory> eipSpecHistories) {
		this.eipSpecHistories = eipSpecHistories;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public void setIsp(Integer isp) {
		this.isp = isp;
	}

	public void setBrand(Integer brand) {
		this.brand = brand;
	}

}
