package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Elb generated by hbm2java
 */
@Entity
@Table(name = "elb", schema = "public")
public class Elb extends BasicEntity {

	private Set<ElbHistory> elbHistories = new HashSet<ElbHistory>(0);
	private Integer ipaddress;
	private Boolean isSession;
	private String remark;
	private Integer tag;
	private Integer tenants;

	public Elb() {
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "elb")
	public Set<ElbHistory> getElbHistories() {
		return this.elbHistories;
	}

	@Column(name = "ipaddress")
	public Integer getIpaddress() {
		return this.ipaddress;
	}

	@Column(name = "is_session")
	public Boolean getIsSession() {
		return this.isSession;
	}

	@Column(name = "\"Remark\"", length = 250)
	public String getRemark() {
		return this.remark;
	}

	@Column(name = "tag")
	public Integer getTag() {
		return this.tag;
	}

	@Column(name = "tenants")
	public Integer getTenants() {
		return this.tenants;
	}

	public void setElbHistories(Set<ElbHistory> elbHistories) {
		this.elbHistories = elbHistories;
	}

	public void setIpaddress(Integer ipaddress) {
		this.ipaddress = ipaddress;
	}

	public void setIsSession(Boolean isSession) {
		this.isSession = isSession;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public void setTag(Integer tag) {
		this.tag = tag;
	}

	public void setTenants(Integer tenants) {
		this.tenants = tenants;
	}

}
