package com.sobey.cmdbuild.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ElbPolicyHistory generated by hbm2java
 */
@Entity
@Table(name = "elb_policy_history", schema = "public")
public class ElbPolicyHistory extends BasicEntity {

	private Integer elb;
	private ElbPolicy elbPolicy;
	private Date endDate;
	private Integer protocol;
	private Integer sourcePort;
	private Integer targetPort;

	public ElbPolicyHistory() {
	}

	@Column(name = "elb")
	public Integer getElb() {
		return this.elb;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public ElbPolicy getElbPolicy() {
		return this.elbPolicy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"EndDate\"", nullable = false, length = 29)
	public Date getEndDate() {
		return this.endDate;
	}

	@Column(name = "protocol")
	public Integer getProtocol() {
		return this.protocol;
	}

	@Column(name = "source_port")
	public Integer getSourcePort() {
		return this.sourcePort;
	}

	@Column(name = "target_port")
	public Integer getTargetPort() {
		return this.targetPort;
	}

	public void setElb(Integer elb) {
		this.elb = elb;
	}

	public void setElbPolicy(ElbPolicy elbPolicy) {
		this.elbPolicy = elbPolicy;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public void setProtocol(Integer protocol) {
		this.protocol = protocol;
	}

	public void setSourcePort(Integer sourcePort) {
		this.sourcePort = sourcePort;
	}

	public void setTargetPort(Integer targetPort) {
		this.targetPort = targetPort;
	}

}
