package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ElbPolicy generated by hbm2java
 */
@Entity
@Table(name = "elb_policy", schema = "public")
public class ElbPolicy extends BasicEntity {

	private Integer elb;
	private Set<ElbPolicyHistory> elbPolicyHistories = new HashSet<ElbPolicyHistory>(0);
	private Integer protocol;
	private Integer sourcePort;
	private Integer targetPort;

	public ElbPolicy() {
	}

	@Column(name = "elb")
	public Integer getElb() {
		return this.elb;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "elbPolicy")
	public Set<ElbPolicyHistory> getElbPolicyHistories() {
		return this.elbPolicyHistories;
	}

	@Column(name = "protocol")
	public Integer getProtocol() {
		return this.protocol;
	}

	@Column(name = "source_port")
	public Integer getSourcePort() {
		return this.sourcePort;
	}

	@Column(name = "target_port")
	public Integer getTargetPort() {
		return this.targetPort;
	}

	public void setElb(Integer elb) {
		this.elb = elb;
	}

	public void setElbPolicyHistories(Set<ElbPolicyHistory> elbPolicyHistories) {
		this.elbPolicyHistories = elbPolicyHistories;
	}

	public void setProtocol(Integer protocol) {
		this.protocol = protocol;
	}

	public void setSourcePort(Integer sourcePort) {
		this.sourcePort = sourcePort;
	}

	public void setTargetPort(Integer targetPort) {
		this.targetPort = targetPort;
	}

}
