package com.sobey.cmdbuild.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;

import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Es3Spec generated by hbm2java
 */
@Entity
@Table(name = "es3_spec", schema = "public")
public class Es3Spec extends BasicEntity {

	private Set<Es3SpecHistory> es3SpecHistories = new HashSet<Es3SpecHistory>(0);
	private Double price;
	private String remark;

	public Es3Spec() {
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"BeginDate\"", nullable = false, length = 29)
	public Date getBeginDate() {
		return this.beginDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "es3Spec")
	public Set<Es3SpecHistory> getEs3SpecHistories() {
		return this.es3SpecHistories;
	}

	@Column(name = "\"Price\"", precision = 17, scale = 17)
	public Double getPrice() {
		return this.price;
	}

	@Column(name = "\"Remark\"", length = 250)
	public String getRemark() {
		return this.remark;
	}

	public void setEs3SpecHistories(Set<Es3SpecHistory> es3SpecHistories) {
		this.es3SpecHistories = es3SpecHistories;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
