package com.sobey.cmdbuild.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;

import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EsgPolicy generated by hbm2java
 */
@Entity
@Table(name = "esg_policy", schema = "public")
public class EsgPolicy extends BasicEntity {

	private Integer esg;
	private Set<EsgPolicyHistory> esgPolicyHistories = new HashSet<EsgPolicyHistory>(0);
	private Integer esgProtocol;
	private Integer port;
	private String sourceIp;
	private String targetIp;

	public EsgPolicy() {
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"BeginDate\"", nullable = false, length = 29)
	public Date getBeginDate() {
		return this.beginDate;
	}

	@Column(name = "esg")
	public Integer getEsg() {
		return this.esg;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "esgPolicy")
	public Set<EsgPolicyHistory> getEsgPolicyHistories() {
		return this.esgPolicyHistories;
	}

	@Column(name = "esg_protocol")
	public Integer getEsgProtocol() {
		return this.esgProtocol;
	}

	@Column(name = "port")
	public Integer getPort() {
		return this.port;
	}

	@Column(name = "source_ip", length = 50)
	public String getSourceIp() {
		return this.sourceIp;
	}

	@Column(name = "target_ip", length = 50)
	public String getTargetIp() {
		return this.targetIp;
	}

	public void setEsg(Integer esg) {
		this.esg = esg;
	}

	public void setEsgPolicyHistories(Set<EsgPolicyHistory> esgPolicyHistories) {
		this.esgPolicyHistories = esgPolicyHistories;
	}

	public void setEsgProtocol(Integer esgProtocol) {
		this.esgProtocol = esgProtocol;
	}

	public void setPort(Integer port) {
		this.port = port;
	}

	public void setSourceIp(String sourceIp) {
		this.sourceIp = sourceIp;
	}

	public void setTargetIp(String targetIp) {
		this.targetIp = targetIp;
	}

}
