package com.sobey.cmdbuild.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EsgPolicyHistory generated by hbm2java
 */
@Entity
@Table(name = "esg_policy_history", schema = "public")
public class EsgPolicyHistory extends BasicEntity {

	private Date endDate;
	private Integer esg;
	private EsgPolicy esgPolicy;
	private Integer esgProtocol;
	private Integer port;
	private String sourceIp;
	private String targetIp;

	public EsgPolicyHistory() {
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"EndDate\"", nullable = false, length = 29)
	public Date getEndDate() {
		return this.endDate;
	}

	@Column(name = "esg")
	public Integer getEsg() {
		return this.esg;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public EsgPolicy getEsgPolicy() {
		return this.esgPolicy;
	}

	@Column(name = "esg_protocol")
	public Integer getEsgProtocol() {
		return this.esgProtocol;
	}

	@Column(name = "port")
	public Integer getPort() {
		return this.port;
	}

	@Column(name = "source_ip", length = 50)
	public String getSourceIp() {
		return this.sourceIp;
	}

	@Column(name = "target_ip", length = 50)
	public String getTargetIp() {
		return this.targetIp;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public void setEsg(Integer esg) {
		this.esg = esg;
	}

	public void setEsgPolicy(EsgPolicy esgPolicy) {
		this.esgPolicy = esgPolicy;
	}

	public void setEsgProtocol(Integer esgProtocol) {
		this.esgProtocol = esgProtocol;
	}

	public void setPort(Integer port) {
		this.port = port;
	}

	public void setSourceIp(String sourceIp) {
		this.sourceIp = sourceIp;
	}

	public void setTargetIp(String targetIp) {
		this.targetIp = targetIp;
	}

}
