package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FirewallPort generated by hbm2java
 */
@Entity
@Table(name = "firewall_port", schema = "public")
public class FirewallPort extends BasicEntity {

	private Integer connectedTo;
	private Integer firewall;
	private Set<FirewallPortHistory> firewallPortHistories = new HashSet<FirewallPortHistory>(0);
	private Integer ipaddress;
	private String macAddress;
	private String remark;
	private String site;

	public FirewallPort() {
	}

	@Column(name = "connected_to")
	public Integer getConnectedTo() {
		return this.connectedTo;
	}

	@Column(name = "firewall")
	public Integer getFirewall() {
		return this.firewall;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "firewallPort")
	public Set<FirewallPortHistory> getFirewallPortHistories() {
		return this.firewallPortHistories;
	}

	@Column(name = "ipaddress")
	public Integer getIpaddress() {
		return this.ipaddress;
	}

	@Column(name = "mac_address", length = 50)
	public String getMacAddress() {
		return this.macAddress;
	}

	@Column(name = "\"Remark\"", length = 50)
	public String getRemark() {
		return this.remark;
	}

	@Column(name = "\"Site\"", length = 50)
	public String getSite() {
		return this.site;
	}

	public void setConnectedTo(Integer connectedTo) {
		this.connectedTo = connectedTo;
	}

	public void setFirewall(Integer firewall) {
		this.firewall = firewall;
	}

	public void setFirewallPortHistories(Set<FirewallPortHistory> firewallPortHistories) {
		this.firewallPortHistories = firewallPortHistories;
	}

	public void setIpaddress(Integer ipaddress) {
		this.ipaddress = ipaddress;
	}

	public void setMacAddress(String macAddress) {
		this.macAddress = macAddress;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public void setSite(String site) {
		this.site = site;
	}

}
