package com.sobey.cmdbuild.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;

import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GroupPolicy generated by hbm2java
 */
@Entity
@Table(name = "group_policy", schema = "public")
public class GroupPolicy extends BasicEntity {

	private Set<GroupPolicyHistory> groupPolicyHistories = new HashSet<GroupPolicyHistory>(0);
	private String remark;
	private Integer tenants;

	public GroupPolicy() {
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"BeginDate\"", nullable = false, length = 29)
	public Date getBeginDate() {
		return this.beginDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupPolicy")
	public Set<GroupPolicyHistory> getGroupPolicyHistories() {
		return this.groupPolicyHistories;
	}

	@Column(name = "\"Remark\"", length = 250)
	public String getRemark() {
		return this.remark;
	}

	@Column(name = "tenants")
	public Integer getTenants() {
		return this.tenants;
	}

	public void setGroupPolicyHistories(Set<GroupPolicyHistory> groupPolicyHistories) {
		this.groupPolicyHistories = groupPolicyHistories;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public void setTenants(Integer tenants) {
		this.tenants = tenants;
	}

}
