package com.sobey.cmdbuild.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HardDiskHistory generated by hbm2java
 */
@Entity
@Table(name = "hard_disk_history", schema = "public")
public class HardDiskHistory extends BasicEntity {

	private Integer brand;
	private Date endDate;
	private Integer fimas;
	private HardDisk hardDisk;
	private Integer hardDiskSize;
	private Integer idc;
	private Integer rotationalSpeed;
	private Integer server;

	public HardDiskHistory() {
	}

	@Column(name = "\"Brand\"")
	public Integer getBrand() {
		return this.brand;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"EndDate\"", nullable = false, length = 29)
	public Date getEndDate() {
		return this.endDate;
	}

	@Column(name = "fimas")
	public Integer getFimas() {
		return this.fimas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public HardDisk getHardDisk() {
		return this.hardDisk;
	}

	@Column(name = "\"hardDisk_size\"")
	public Integer getHardDiskSize() {
		return this.hardDiskSize;
	}

	@Column(name = "\"IDC\"")
	public Integer getIdc() {
		return this.idc;
	}

	@Column(name = "rotational_speed")
	public Integer getRotationalSpeed() {
		return this.rotationalSpeed;
	}

	@Column(name = "server")
	public Integer getServer() {
		return this.server;
	}

	public void setBrand(Integer brand) {
		this.brand = brand;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public void setFimas(Integer fimas) {
		this.fimas = fimas;
	}

	public void setHardDisk(HardDisk hardDisk) {
		this.hardDisk = hardDisk;
	}

	public void setHardDiskSize(Integer hardDiskSize) {
		this.hardDiskSize = hardDiskSize;
	}

	public void setIdc(Integer idc) {
		this.idc = idc;
	}

	public void setRotationalSpeed(Integer rotationalSpeed) {
		this.rotationalSpeed = rotationalSpeed;
	}

	public void setServer(Integer server) {
		this.server = server;
	}

}
