package com.sobey.cmdbuild.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;

import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HardDiskHistory generated by hbm2java
 */
@Entity
@Table(name = "hard_disk_history", schema = "public")
public class HardDiskHistory extends BasicEntity {

	private Integer brand;
	private Date endDate;
	private Integer fimas;
	private HardDisk hardDisk;
	private Integer hardDiskSize;
	private Integer idc;
	private Integer rotationalSpeed;
	private Integer server;

	public HardDiskHistory() {
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"BeginDate\"", nullable = false, length = 29)
	public Date getBeginDate() {
		return this.beginDate;
	}

	@Column(name = "\"Brand\"")
	public Integer getBrand() {
		return this.brand;
	}

	@Column(name = "\"Code\"", length = 100)
	public String getCode() {
		return this.code;
	}

	@Column(name = "\"Description\"", length = 250)
	public String getDescription() {
		return this.description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"EndDate\"", nullable = false, length = 29)
	public Date getEndDate() {
		return this.endDate;
	}

	@Column(name = "fimas")
	public Integer getFimas() {
		return this.fimas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public HardDisk getHardDisk() {
		return this.hardDisk;
	}

	@Column(name = "hardDisk_size")
	public Integer getHardDiskSize() {
		return this.hardDiskSize;
	}

	@Column(name = "\"IDC\"")
	public Integer getIdc() {
		return this.idc;
	}

	@Column(name = "\"Notes\"")
	public String getNotes() {
		return this.notes;
	}

	@Column(name = "rotational_speed")
	public Integer getRotationalSpeed() {
		return this.rotationalSpeed;
	}

	@Column(name = "server")
	public Integer getServer() {
		return this.server;
	}

	@Column(name = "\"Status\"", length = 1)
	public Character getStatus() {
		return this.status;
	}

	@Column(name = "\"User\"", length = 40)
	public String getUser() {
		return this.user;
	}

	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	public void setBrand(Integer brand) {
		this.brand = brand;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public void setFimas(Integer fimas) {
		this.fimas = fimas;
	}

	public void setHardDisk(HardDisk hardDisk) {
		this.hardDisk = hardDisk;
	}

	public void setHardDiskSize(Integer hardDiskSize) {
		this.hardDiskSize = hardDiskSize;
	}

	public void setIdc(Integer idc) {
		this.idc = idc;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public void setRotationalSpeed(Integer rotationalSpeed) {
		this.rotationalSpeed = rotationalSpeed;
	}

	public void setServer(Integer server) {
		this.server = server;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	public void setUser(String user) {
		this.user = user;
	}

}
