package com.sobey.cmdbuild.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;

import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HardDisk generated by hbm2java
 */
@Entity
@Table(name = "hard_disk", schema = "public")
public class HardDisk extends BasicEntity {

	private Integer brand;
	private Integer fimas;
	private Set<HardDiskHistory> hardDiskHistories = new HashSet<HardDiskHistory>(0);
	private Integer hardDiskSize;
	private Integer idc;
	private Integer rotationalSpeed;
	private Integer server;

	public HardDisk() {
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"BeginDate\"", nullable = false, length = 29)
	public Date getBeginDate() {
		return this.beginDate;
	}

	@Column(name = "\"Brand\"")
	public Integer getBrand() {
		return this.brand;
	}

	@Column(name = "fimas")
	public Integer getFimas() {
		return this.fimas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hardDisk")
	public Set<HardDiskHistory> getHardDiskHistories() {
		return this.hardDiskHistories;
	}

	@Column(name = "hardDisk_size")
	public Integer getHardDiskSize() {
		return this.hardDiskSize;
	}

	@Column(name = "\"IDC\"")
	public Integer getIdc() {
		return this.idc;
	}

	@Column(name = "rotational_speed")
	public Integer getRotationalSpeed() {
		return this.rotationalSpeed;
	}

	@Column(name = "server")
	public Integer getServer() {
		return this.server;
	}

	public void setBrand(Integer brand) {
		this.brand = brand;
	}

	public void setFimas(Integer fimas) {
		this.fimas = fimas;
	}

	public void setHardDiskHistories(Set<HardDiskHistory> hardDiskHistories) {
		this.hardDiskHistories = hardDiskHistories;
	}

	public void setHardDiskSize(Integer hardDiskSize) {
		this.hardDiskSize = hardDiskSize;
	}

	public void setIdc(Integer idc) {
		this.idc = idc;
	}

	public void setRotationalSpeed(Integer rotationalSpeed) {
		this.rotationalSpeed = rotationalSpeed;
	}

	public void setServer(Integer server) {
		this.server = server;
	}

}
