package com.sobey.cmdbuild.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;

import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoadBalancerPort generated by hbm2java
 */
@Entity
@Table(name = "load_balancer_port", schema = "public")
public class LoadBalancerPort extends BasicEntity {

	private Integer connectedTo;
	private Integer ipaddress;
	private Integer loadBalancer;
	private Set<LoadBalancerPortHistory> loadBalancerPortHistories = new HashSet<LoadBalancerPortHistory>(0);
	private String macAddress;
	private String remark;
	private String site;

	public LoadBalancerPort() {
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"BeginDate\"", nullable = false, length = 29)
	public Date getBeginDate() {
		return this.beginDate;
	}

	@Column(name = "connected_to")
	public Integer getConnectedTo() {
		return this.connectedTo;
	}

	@Column(name = "ipaddress")
	public Integer getIpaddress() {
		return this.ipaddress;
	}

	@Column(name = "load_balancer")
	public Integer getLoadBalancer() {
		return this.loadBalancer;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loadBalancerPort")
	public Set<LoadBalancerPortHistory> getLoadBalancerPortHistories() {
		return this.loadBalancerPortHistories;
	}

	@Column(name = "mac_address", length = 50)
	public String getMacAddress() {
		return this.macAddress;
	}

	@Column(name = "\"Remark\"", length = 50)
	public String getRemark() {
		return this.remark;
	}

	@Column(name = "\"Site\"", length = 50)
	public String getSite() {
		return this.site;
	}

	public void setConnectedTo(Integer connectedTo) {
		this.connectedTo = connectedTo;
	}

	public void setIpaddress(Integer ipaddress) {
		this.ipaddress = ipaddress;
	}

	public void setLoadBalancer(Integer loadBalancer) {
		this.loadBalancer = loadBalancer;
	}

	public void setLoadBalancerPortHistories(Set<LoadBalancerPortHistory> loadBalancerPortHistories) {
		this.loadBalancerPortHistories = loadBalancerPortHistories;
	}

	public void setMacAddress(String macAddress) {
		this.macAddress = macAddress;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public void setSite(String site) {
		this.site = site;
	}

}
