package com.sobey.cmdbuild.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;

import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MemoryHistory generated by hbm2java
 */
@Entity
@Table(name = "memory_history", schema = "public")
public class MemoryHistory extends BasicEntity {

	private Integer brand;

	private Date endDate;
	private Integer fimas;
	private Integer frequency;
	private Integer idc;
	private Memory memory;
	private Integer ram;
	private Integer server;

	public MemoryHistory() {
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"BeginDate\"", nullable = false, length = 29)
	public Date getBeginDate() {
		return this.beginDate;
	}

	@Column(name = "\"Brand\"")
	public Integer getBrand() {
		return this.brand;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"EndDate\"", nullable = false, length = 29)
	public Date getEndDate() {
		return this.endDate;
	}

	@Column(name = "fimas")
	public Integer getFimas() {
		return this.fimas;
	}

	@Column(name = "\"Frequency\"")
	public Integer getFrequency() {
		return this.frequency;
	}

	@Column(name = "\"IDC\"")
	public Integer getIdc() {
		return this.idc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public Memory getMemory() {
		return this.memory;
	}

	@Column(name = "ram")
	public Integer getRam() {
		return this.ram;
	}

	@Column(name = "server")
	public Integer getServer() {
		return this.server;
	}

	public void setBrand(Integer brand) {
		this.brand = brand;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public void setFimas(Integer fimas) {
		this.fimas = fimas;
	}

	public void setFrequency(Integer frequency) {
		this.frequency = frequency;
	}

	public void setIdc(Integer idc) {
		this.idc = idc;
	}

	public void setMemory(Memory memory) {
		this.memory = memory;
	}

	public void setRam(Integer ram) {
		this.ram = ram;
	}

	public void setServer(Integer server) {
		this.server = server;
	}

}
