package com.sobey.cmdbuild.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;

import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Memory generated by hbm2java
 */
@Entity
@Table(name = "memory", schema = "public")
public class Memory extends BasicEntity {

	private Integer brand;
	private Integer fimas;
	private Integer frequency;
	private Integer idc;
	private Set<MemoryHistory> memoryHistories = new HashSet<MemoryHistory>(0);
	private Integer ram;
	private Integer server;

	public Memory() {
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"BeginDate\"", nullable = false, length = 29)
	public Date getBeginDate() {
		return this.beginDate;
	}

	@Column(name = "\"Brand\"")
	public Integer getBrand() {
		return this.brand;
	}

	@Column(name = "\"Code\"", length = 100)
	public String getCode() {
		return this.code;
	}

	@Column(name = "\"Description\"", length = 250)
	public String getDescription() {
		return this.description;
	}

	@Column(name = "fimas")
	public Integer getFimas() {
		return this.fimas;
	}

	@Column(name = "\"Frequency\"")
	public Integer getFrequency() {
		return this.frequency;
	}

	@Column(name = "\"IDC\"")
	public Integer getIdc() {
		return this.idc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "memory")
	public Set<MemoryHistory> getMemoryHistories() {
		return this.memoryHistories;
	}

	@Column(name = "\"Notes\"")
	public String getNotes() {
		return this.notes;
	}

	@Column(name = "ram")
	public Integer getRam() {
		return this.ram;
	}

	@Column(name = "server")
	public Integer getServer() {
		return this.server;
	}

	@Column(name = "\"Status\"", length = 1)
	public Character getStatus() {
		return this.status;
	}

	@Column(name = "\"User\"", length = 40)
	public String getUser() {
		return this.user;
	}

	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	public void setBrand(Integer brand) {
		this.brand = brand;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setFimas(Integer fimas) {
		this.fimas = fimas;
	}

	public void setFrequency(Integer frequency) {
		this.frequency = frequency;
	}

	public void setIdc(Integer idc) {
		this.idc = idc;
	}

	public void setMemoryHistories(Set<MemoryHistory> memoryHistories) {
		this.memoryHistories = memoryHistories;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public void setRam(Integer ram) {
		this.ram = ram;
	}

	public void setServer(Integer server) {
		this.server = server;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	public void setUser(String user) {
		this.user = user;
	}

}
