package com.sobey.cmdbuild.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;

import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NetappBox generated by hbm2java
 */
@Entity
@Table(name = "netapp_box", schema = "public")
public class NetappBox extends BasicEntity {

	private Integer deviceSpec;
	private Integer diskNumber;
	private Integer diskType;
	private String gdzcSn;
	private Integer idc;
	private Integer ipaddress;
	private Set<NetappBoxHistory> netappBoxHistories = new HashSet<NetappBoxHistory>(0);
	private Integer rack;
	private String remark;
	private String site;
	private String sn;

	public NetappBox() {
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"BeginDate\"", nullable = false, length = 29)
	public Date getBeginDate() {
		return this.beginDate;
	}

	@Column(name = "device_spec")
	public Integer getDeviceSpec() {
		return this.deviceSpec;
	}

	@Column(name = "disk_number")
	public Integer getDiskNumber() {
		return this.diskNumber;
	}

	@Column(name = "disk_type")
	public Integer getDiskType() {
		return this.diskType;
	}

	@Column(name = "\"GdzcSn\"", length = 50)
	public String getGdzcSn() {
		return this.gdzcSn;
	}

	@Column(name = "\"IDC\"")
	public Integer getIdc() {
		return this.idc;
	}

	@Column(name = "ipaddress")
	public Integer getIpaddress() {
		return this.ipaddress;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "netappBox")
	public Set<NetappBoxHistory> getNetappBoxHistories() {
		return this.netappBoxHistories;
	}

	@Column(name = "rack")
	public Integer getRack() {
		return this.rack;
	}

	@Column(name = "\"Remark\"", length = 250)
	public String getRemark() {
		return this.remark;
	}

	@Column(name = "\"Site\"", length = 50)
	public String getSite() {
		return this.site;
	}

	@Column(name = "\"SN\"", length = 50)
	public String getSn() {
		return this.sn;
	}

	public void setDeviceSpec(Integer deviceSpec) {
		this.deviceSpec = deviceSpec;
	}

	public void setDiskNumber(Integer diskNumber) {
		this.diskNumber = diskNumber;
	}

	public void setDiskType(Integer diskType) {
		this.diskType = diskType;
	}

	public void setGdzcSn(String gdzcSn) {
		this.gdzcSn = gdzcSn;
	}

	public void setIdc(Integer idc) {
		this.idc = idc;
	}

	public void setIpaddress(Integer ipaddress) {
		this.ipaddress = ipaddress;
	}

	public void setNetappBoxHistories(Set<NetappBoxHistory> netappBoxHistories) {
		this.netappBoxHistories = netappBoxHistories;
	}

	public void setRack(Integer rack) {
		this.rack = rack;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public void setSite(String site) {
		this.site = site;
	}

	public void setSn(String sn) {
		this.sn = sn;
	}

}
