package com.sobey.cmdbuild.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;

import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Nic generated by hbm2java
 */
@Entity
@Table(name = "nic", schema = "public")
public class Nic extends BasicEntity {

	private Integer brand;
	private Integer fimas;
	private Integer idc;
	private Set<NicHistory> nicHistories = new HashSet<NicHistory>(0);
	private Integer nicRate;
	private Integer portNumber;
	private Integer server;

	public Nic() {
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"BeginDate\"", nullable = false, length = 29)
	public Date getBeginDate() {
		return this.beginDate;
	}

	@Column(name = "\"Brand\"")
	public Integer getBrand() {
		return this.brand;
	}

	@Column(name = "\"Code\"", length = 100)
	public String getCode() {
		return this.code;
	}

	@Column(name = "\"Description\"", length = 250)
	public String getDescription() {
		return this.description;
	}

	@Column(name = "fimas")
	public Integer getFimas() {
		return this.fimas;
	}

	@Column(name = "\"IDC\"")
	public Integer getIdc() {
		return this.idc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nic")
	public Set<NicHistory> getNicHistories() {
		return this.nicHistories;
	}

	@Column(name = "nic_rate")
	public Integer getNicRate() {
		return this.nicRate;
	}

	@Column(name = "\"Notes\"")
	public String getNotes() {
		return this.notes;
	}

	@Column(name = "port_number")
	public Integer getPortNumber() {
		return this.portNumber;
	}

	@Column(name = "server")
	public Integer getServer() {
		return this.server;
	}

	@Column(name = "\"Status\"", length = 1)
	public Character getStatus() {
		return this.status;
	}

	@Column(name = "\"User\"", length = 40)
	public String getUser() {
		return this.user;
	}

	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	public void setBrand(Integer brand) {
		this.brand = brand;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setFimas(Integer fimas) {
		this.fimas = fimas;
	}

	public void setIdc(Integer idc) {
		this.idc = idc;
	}

	public void setNicHistories(Set<NicHistory> nicHistories) {
		this.nicHistories = nicHistories;
	}

	public void setNicRate(Integer nicRate) {
		this.nicRate = nicRate;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public void setPortNumber(Integer portNumber) {
		this.portNumber = portNumber;
	}

	public void setServer(Integer server) {
		this.server = server;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	public void setUser(String user) {
		this.user = user;
	}

}
