package com.sobey.cmdbuild.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;

import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NicHistory generated by hbm2java
 */
@Entity
@Table(name = "nic_history", schema = "public")
public class NicHistory extends BasicEntity {

	private Integer brand;
	private Date endDate;
	private Integer fimas;
	private Integer idc;
	private Nic nic;
	private Integer nicRate;
	private Integer portNumber;
	private Integer server;

	public NicHistory() {
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"BeginDate\"", nullable = false, length = 29)
	public Date getBeginDate() {
		return this.beginDate;
	}

	@Column(name = "\"Brand\"")
	public Integer getBrand() {
		return this.brand;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"EndDate\"", nullable = false, length = 29)
	public Date getEndDate() {
		return this.endDate;
	}

	@Column(name = "fimas")
	public Integer getFimas() {
		return this.fimas;
	}

	@Column(name = "\"IDC\"")
	public Integer getIdc() {
		return this.idc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public Nic getNic() {
		return this.nic;
	}

	@Column(name = "nic_rate")
	public Integer getNicRate() {
		return this.nicRate;
	}

	@Column(name = "port_number")
	public Integer getPortNumber() {
		return this.portNumber;
	}

	@Column(name = "server")
	public Integer getServer() {
		return this.server;
	}

	public void setBrand(Integer brand) {
		this.brand = brand;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public void setFimas(Integer fimas) {
		this.fimas = fimas;
	}

	public void setIdc(Integer idc) {
		this.idc = idc;
	}

	public void setNic(Nic nic) {
		this.nic = nic;
	}

	public void setNicRate(Integer nicRate) {
		this.nicRate = nicRate;
	}

	public void setPortNumber(Integer portNumber) {
		this.portNumber = portNumber;
	}

	public void setServer(Integer server) {
		this.server = server;
	}

}
