package com.sobey.cmdbuild.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NicPort generated by hbm2java
 */
@Entity
@Table(name = "nic_port", schema = "public")
public class NicPort extends BasicEntity {

	private Integer connectedTo;
	private Integer ipaddress;
	private String macAddress;
	private Integer nic;
	private Set<NicPortHistory> nicPortHistories = new HashSet<NicPortHistory>(0);
	private String remark;
	private String site;

	public NicPort() {
	}

	@Column(name = "connected_to")
	public Integer getConnectedTo() {
		return this.connectedTo;
	}

	@Column(name = "ipaddress")
	public Integer getIpaddress() {
		return this.ipaddress;
	}

	@Column(name = "mac_address", length = 50)
	public String getMacAddress() {
		return this.macAddress;
	}

	@Column(name = "nic")
	public Integer getNic() {
		return this.nic;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nicPort")
	public Set<NicPortHistory> getNicPortHistories() {
		return this.nicPortHistories;
	}

	@Column(name = "\"Remark\"", length = 50)
	public String getRemark() {
		return this.remark;
	}

	@Column(name = "\"Site\"", length = 50)
	public String getSite() {
		return this.site;
	}

	public void setConnectedTo(Integer connectedTo) {
		this.connectedTo = connectedTo;
	}

	public void setIpaddress(Integer ipaddress) {
		this.ipaddress = ipaddress;
	}

	public void setMacAddress(String macAddress) {
		this.macAddress = macAddress;
	}

	public void setNic(Integer nic) {
		this.nic = nic;
	}

	public void setNicPortHistories(Set<NicPortHistory> nicPortHistories) {
		this.nicPortHistories = nicPortHistories;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public void setSite(String site) {
		this.site = site;
	}

}
