package com.sobey.cmdbuild.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RackHistory generated by hbm2java
 */
@Entity
@Table(name = "rack_history", schema = "public")
public class RackHistory extends BasicEntity {

	private Integer brand;
	private Date endDate;
	private String gdzcSn;
	private Integer height;
	private Integer idc;
	private String model;
	private Integer power;
	private Double price;
	private Rack rack;
	private String remark;
	private String sn;
	private Integer unitNumber;

	public RackHistory() {
	}

	@Column(name = "\"Brand\"")
	public Integer getBrand() {
		return this.brand;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"EndDate\"", nullable = false, length = 29)
	public Date getEndDate() {
		return this.endDate;
	}

	@Column(name = "\"GdzcSn\"", length = 100)
	public String getGdzcSn() {
		return this.gdzcSn;
	}

	@Column(name = "\"Height\"")
	public Integer getHeight() {
		return this.height;
	}

	@Column(name = "idc")
	public Integer getIdc() {
		return this.idc;
	}

	@Column(name = "\"Model\"", length = 100)
	public String getModel() {
		return this.model;
	}

	@Column(name = "\"Power\"")
	public Integer getPower() {
		return this.power;
	}

	@Column(name = "\"Price\"", precision = 17, scale = 17)
	public Double getPrice() {
		return this.price;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public Rack getRack() {
		return this.rack;
	}

	@Column(name = "\"Remark\"", length = 250)
	public String getRemark() {
		return this.remark;
	}

	@Column(name = "\"SN\"", length = 100)
	public String getSn() {
		return this.sn;
	}

	@Column(name = "unit_number")
	public Integer getUnitNumber() {
		return this.unitNumber;
	}

	public void setBrand(Integer brand) {
		this.brand = brand;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public void setGdzcSn(String gdzcSn) {
		this.gdzcSn = gdzcSn;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	public void setIdc(Integer idc) {
		this.idc = idc;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public void setPower(Integer power) {
		this.power = power;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public void setRack(Rack rack) {
		this.rack = rack;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public void setSn(String sn) {
		this.sn = sn;
	}

	public void setUnitNumber(Integer unitNumber) {
		this.unitNumber = unitNumber;
	}

}
