package com.sobey.cmdbuild.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;

import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VlanHistory generated by hbm2java
 */
@Entity
@Table(name = "vlan_history", schema = "public")
public class VlanHistory extends BasicEntity {

	private Date endDate;
	private String gateway;
	private Integer idc;
	private String netMask;
	private String remark;
	private String segment;
	private Vlan vlan;

	public VlanHistory() {
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"BeginDate\"", nullable = false, length = 29)
	public Date getBeginDate() {
		return this.beginDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"EndDate\"", nullable = false, length = 29)
	public Date getEndDate() {
		return this.endDate;
	}

	@Column(name = "gateway", length = 50)
	public String getGateway() {
		return this.gateway;
	}

	@Column(name = "\"IDC\"")
	public Integer getIdc() {
		return this.idc;
	}

	@Column(name = "net_mask", length = 50)
	public String getNetMask() {
		return this.netMask;
	}

	@Column(name = "\"Remark\"", length = 250)
	public String getRemark() {
		return this.remark;
	}

	@Column(name = "segment", length = 50)
	public String getSegment() {
		return this.segment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "\"CurrentId\"", nullable = false)
	public Vlan getVlan() {
		return this.vlan;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public void setGateway(String gateway) {
		this.gateway = gateway;
	}

	public void setIdc(Integer idc) {
		this.idc = idc;
	}

	public void setNetMask(String netMask) {
		this.netMask = netMask;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public void setSegment(String segment) {
		this.segment = segment;
	}

	public void setVlan(Vlan vlan) {
		this.vlan = vlan;
	}

}
