package com.sobey.cmdbuild.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;

import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vpn generated by hbm2java
 */
@Entity
@Table(name = "vpn", schema = "public")
public class Vpn extends BasicEntity {

	private String remark;
	private Integer tag;
	private Integer tenants;
	private Set<VpnHistory> vpnHistories = new HashSet<VpnHistory>(0);
	private String vpnName;
	private String vpnPassword;

	public Vpn() {
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"BeginDate\"", nullable = false, length = 29)
	public Date getBeginDate() {
		return this.beginDate;
	}

	@Column(name = "\"Code\"", length = 100)
	public String getCode() {
		return this.code;
	}

	@Column(name = "\"Description\"", length = 250)
	public String getDescription() {
		return this.description;
	}

	@Column(name = "\"Notes\"")
	public String getNotes() {
		return this.notes;
	}

	@Column(name = "\"Remark\"", length = 250)
	public String getRemark() {
		return this.remark;
	}

	@Column(name = "\"Status\"", length = 1)
	public Character getStatus() {
		return this.status;
	}

	@Column(name = "tag")
	public Integer getTag() {
		return this.tag;
	}

	@Column(name = "tenants")
	public Integer getTenants() {
		return this.tenants;
	}

	@Column(name = "\"User\"", length = 40)
	public String getUser() {
		return this.user;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vpn")
	public Set<VpnHistory> getVpnHistories() {
		return this.vpnHistories;
	}

	@Column(name = "vpn_name", length = 100)
	public String getVpnName() {
		return this.vpnName;
	}

	@Column(name = "vpn_password", length = 100)
	public String getVpnPassword() {
		return this.vpnPassword;
	}

	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	public void setTag(Integer tag) {
		this.tag = tag;
	}

	public void setTenants(Integer tenants) {
		this.tenants = tenants;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public void setVpnHistories(Set<VpnHistory> vpnHistories) {
		this.vpnHistories = vpnHistories;
	}

	public void setVpnName(String vpnName) {
		this.vpnName = vpnName;
	}

	public void setVpnPassword(String vpnPassword) {
		this.vpnPassword = vpnPassword;
	}

}
